# .github/workflows/docker-scan.yml
name: Docker Security Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  scan:
    name: Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t weather-api:${{ github.sha }} .

      # Download the official HTML template
      - name: Download Trivy template
        run: |
          wget https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/html.tpl

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'weather-api:${{ github.sha }}'
          format: 'template'
          template: '@html.tpl'
          output: 'trivy-results.html'
          severity: 'CRITICAL,HIGH,MEDIUM'
          timeout: '10m'
          security-checks: 'vuln'  # Only scan for vulnerabilities
          scanners: 'vuln'        # Disable unnecessary scanners

      - name: Upload Trivy scan results
        uses: actions/upload-artifact@v3
        with:
          name: trivy-scan-results
          path: trivy-results.html
          retention-days: 90

